[package]
name = "sql"
version.workspace = true
edition.workspace = true

[dependencies]
dyn-clone = { workspace = true}
serde = { workspace = true, features = ["derive"] }

common_error = { workspace = true }
encoding = { workspace = true }