[package]
name = "raft_db_common"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
bincode.workspace = true
config.workspace = true
crossbeam.workspace = true
hdrhistogram.workspace = true
log.workspace = true
regex.workspace = true
rustyline.workspace = true