//! The planner builds and optimizes an execution plan based on a SQL
//! statement's Abstract Syntax Tree (AST) generated by the parser.

mod plan;
mod planner;
mod optimizer;

pub use plan::{Aggregate, Direction, Node, Plan};
pub use planner::{Planner, Scope};
